import ThymeRegistry from '@/theme/thymeRegistry'
import '../css/reset.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthPtovider } from '@/contexts/authContext'
import CustomSessionProvider from '@/Providers/SessionProvider'
import { getServerSession } from 'next-auth'
// import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <ThymeRegistry>
        <AuthPtovider>
        {/* <CustomSessionProvider session={session}> */}
          <body className={inter.className}>
            {children}
          </body>
        {/* </CustomSessionProvider> */}
        </AuthPtovider>
      </ThymeRegistry>
    </html>
  )
}
